apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: novu-mongodb-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
