version = 1

test_patterns = [
  "apps/api/src/**/**/*.spec.ts",
  "apps/api/e2e/**/*.e2e.ts",
  "apps/api/src/**/*.e2e.ts",
  "apps/web/cypress/**/*.spec.ts",
  "apps/widget/cypress/**/*.spec.ts"
]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "prettier"
enabled = true
